### PR TITLE
Upgrade Prettier to version 2

### PR DESCRIPTION
**Pull request by nickmccurdy**
- Keeps extension's formatting defaults consistent with Prettier's breaking changes
- Simplifies our own scripts and updates our formatting
- Renames parsers

### CODE REVIEW

**Comment by kaicataldo** [comment]
Hmmm looks like Travis is broken?

**Comment by nickmccurdy** [comment]
It seems like this repository is still using the legacy GitHub services integration for Travis, which has not been supported as of January 31st. I've sent a request to the organization admins to add this repository to the GitHub app integration. I believe once that's accepted, we can migrate the existing configuration over and it should start processing builds again.

**Comment by nickmccurdy** [comment]
Apparently the legacy integration is still supposed to post builds, but it has stopped working recently and Travis is working on fixing it. https://www.traviscistatus.com/

**Comment by nickmccurdy** [comment]
Still seems to be broken even though Travis says the issue is fixed, migration is worth trying.

**Comment by lipis** [comment]
We should switch to GitHub actions

**Comment by nickmccurdy** [comment]
Upgraded Prettier to 2.0.2 and fixed the GitHub Actions build

**Pull request merged**
