### PR TITLE
Add type=`button` to rendered prettier buttons

### LINKED ISSUE #44: Button is missing `type="button"` attribute
This means it may submit the form it lives inside, which is probably not desired…

Screen Recording 2019-10-16 at 18 15 12

### PR DESCRIPTION
**Pull request by Wicked7000**
Fixes #44 
Simple change to add the type='button' to our rendered Prettier buttons.

### CODE REVIEW

**Comment by nickmccurdy** [comment]
I tried this myself, but when I press the Prettier button in a pull request inline comment, nothing happens

**Comment by kaicataldo** [comment]
I'm seeing the same behavior as `nickmccurdy` - I don't think this is the fix we want. The behavior this is trying to fix didn't occur in the original implementation. I think it's a regression introduced by https://github.com/prettier/prettier-chrome-extension/commit/befe1fbea6c4ebadb3ad0d271046893ce48fd7a7. Maybe we can try to render the buttons in the same place they were before?

**Comment by kaicataldo** [comment]
Looking at this a bit more, it looks like they are rendered in the same parent node. Maybe GitHub's own JS is binding to this button? I don't think this was happening in the initial implementation because the button was rendered lazily and probably was created after GitHub's scripts ran.

Also, definitely not a bad idea to merge this PR - it just doesn't seem to fix the problem.

**Comment by kaicataldo** [comment]
I'm actually not even seeing our button click handler fire at all at this point. Weird - when I tried this out before we merged it seemed to be working?

**Comment by Wicked7000** [comment]
I'll have a look but when I tested it seemed to be rendering and working okay. From what I've found it seems to be the event propagation that's the problem. (That leads to submitting) so I'll shift that up in both click handlers, otherwise if an error does occur it will submit because the prevent propagation statement hasn't been reached.

**Comment by kaicataldo** [comment]
Any idea why the CI branch check is hanging?

**Comment by Wicked7000** [comment]
> Any idea why the CI branch check is hanging?

Possibly could be this?
https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154

**Comment by Wicked7000** [comment]
> I'm actually not even seeing our button click handler fire at all at this point. Weird - when I tried this out before we merged it seemed to be working?

I've tested this out again locally with and without the type='button' and the click handler fires and prevents it from submitting for me?

**Comment by kaicataldo** [comment]
Sorry, should have clarified. The event handler isn't firing for me for individual line comments (clicking the + button on a line) on the code diff view (in PRs and in individual commits).

**Comment by Wicked7000** [comment]
> Sorry, should have clarified. The event handler isn't firing for me for individual line comments (clicking the + button on a line) on the code diff view (in PRs and in individual commits).

No worries, thanks for letting me know. It seems this was some weirdness around the eventListener being added before the DOM was rendered which meant it didn't attach there is some added elements being observed for when the diff view changes which now updates the listeners which fixes this problem

**Comment by nickmccurdy** [comment]
@kaicataldo @lipis Do you have access to the branch settings? It seems like it's needed to fix the Travis CI build. https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154

**Pull request merged**
